Implement WIRELESS_FREQUENCY_LIST to select allowed channels (PED-8715)
openSUSE/wicked pull request #1024
Opened 2024-07-09 12:59 UTC by cfconrad

* introduce new `WIRELESS_FREQUENCY_LIST` and `<frequency-list>`
  * It is possible to specify a frequency directly or use one of the following aliases `2.5GHz`, `5GHz`, `6GHz`.
* add `channel/frequency` info into `wicked ifstatus --verbose wlanX`
* add `frequency` to scan results

### Example wicked ifstatus output:
```bash
tw-1:~ # wicked ifstatus --verbose  wlan1
wlan1           up
      link:     #6, state up, mtu 1500
      type:     wireless, state established, ssid MySSID Muha, WPA2-PSK+WPA-PSK
      wireless: bssid 02:00:00:00:00:00, signal -30, channel 6 (2437MHz), duration 680s
      control:  none

...
```

### Manpage output:
![Screenshot from 2024-07-09 14-19-33](https://github.com/openSUSE/wicked/assets/40127946/f40eef51-e04d-442c-af2a-8019f2cb5f66)

2024-07-11 15:27 UTC, mtomaschewski requested changes
This pull request still needs some work, love and tests (error handling).

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +ni_wireless_band2freq_list(ni_uint_array_t *list, const char *value)
```suggestion
ni_wireless_band2freq_list(ni_uint_array_t *array, const char *value)
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +	static const unsigned int chan_2_4ghz[] = {
This aren't channels but frequencies:

```suggestion
	static const unsigned int freq_set_2_4ghz[] = {
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +	static const unsigned int chan_5ghz[] = {
```suggestion
	static const unsigned int freq_set_5ghz[] = {
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +		const char *name;
```suggestion
		ni_wireless_freqency_set_t	set;
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +		const unsigned int *list;
```suggestion
		const unsigned int *	array;
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +		{ "2.4GHz", chan_2_4ghz},
```suggestion
		{ NI_WIRELESS_FREQUENCY_SET_2_4GHz,	freq_set_2_4ghz	},
```

2024-07-11 15:27 UTC, mtomaschewski commented on src/wireless.c
> +ni_wireless_frequency_list_expand_csv(ni_uint_array_t *expanded_freq, const char *value,
```suggestion
ni_wireless_frequency_list_parse_string(const char *value, ni_uint_array_t *expanded_freq,
```

2024-07-12 09:22 UTC, cfconrad commented on client/suse/compat-suse.c
> +			return FALSE;
Do not invalidate the full config, it is enough to throw a warning for wrong values.

2024-07-12 12:03 UTC, cfconrad commented on schema/wireless.xml
>      <frequency type="double"/>
I didn't wanted to touch this. But If we do so, then I would simply remove this value. As it isn't used elsewhere.

2024-07-16 16:18 UTC, mtomaschewski requested changes
LGTM, thanks!

I'd join the erroneous frequency values consistently with a space as well.

2024-07-16 16:18 UTC, mtomaschewski commented on client/suse/compat-suse.c
> +					ni_stringbuf_join(&tmp, &errors, ","));
I'd use a space " " here as well:
```suggestion
					ni_stringbuf_join(&tmp, &errors, " "));
```

2024-07-16 16:18 UTC, mtomaschewski commented on src/dbus-objects/wireless.c
> +						ni_stringbuf_join(&tmp, &errors, ","),
```suggestion
						ni_stringbuf_join(&tmp, &errors, " "),
```

2024-07-16 16:18 UTC, mtomaschewski commented on src/wireless.c
> +		ni_error("Invalid values in frequency-list: %s", ni_stringbuf_join(&sb, &errors, ","));
```suggestion
		ni_error("Invalid values in frequency-list: %s", ni_stringbuf_join(&sb, &errors, " "));
```

2024-07-16 16:41 UTC, mtomaschewski reviewed
Ahm... almost overlooked it.

2024-07-16 16:41 UTC, mtomaschewski commented on src/dbus-objects/wireless.c
> +						ifname);
-> ifname context first, then (space separated) erroneous frequencies:
```suggestion
				dbus_set_error(error, DBUS_ERROR_INVALID_ARGS,
						"%s: invalid frequency-list value %s",
						ifname, ni_stringbuf_join(&tmp, &errors, " "));
```

2024-07-17 09:43 UTC, cfconrad commented on src/dbus-objects/wireless.c
> +						ifname);
good catch, thx!

2024-07-17 12:59 UTC, mtomaschewski approved these changes
LGTM, thanks!

2024-07-17 13:00 UTC, merged