prepare usrmerge (boo#1029961)
openSUSE/wicked pull request #854
Opened 2020-11-30 16:17 UTC by lnussel

2020-12-02 09:12 UTC, mtomaschewski requested changes
A  pull request which not even provides a short describtion of the intention? Is  the pull not worth to document or not worth to consider at all?

Wicked installs all binaries to `/usr/sbin` **since SLE-12-GA** (and before) -- inclusive of `ifup` wrapper script.
The `/sbin/if{up,down,status,probe}` symlinks and the wrapper script are provided for sysconfig aka **SLE-11 compatibility**, where the scripts were in `/sbin`. It is rather an coincidence, that there were also the *usrmerge* initiative moving things not required at boot to `/usr`.

There is code that is using  the `/sbin/ifup` compatibility wrapper, e.g. `execv("/sbin/ifup", ...),
refering to it, ... which would start to fail without it.
Thus  as long as  we provide such an compatibility, they have to stay in  `/sbin`. When we don't provide the compatibility,  IMO the complete wrapper script and the links can be removed.

2020-12-02 09:16 UTC, mtomaschewski commented
I need a PM approval and thus a feature request in order to remove the SLE-11 `ifup` compatibility -- this is not a bug to provide it and thus the bug is simply invalid.

2020-12-02 09:26 UTC, mtomaschewski commented
IMO a right way to implement a removal of the SLE-11 `ifup` compatibility would be to use conditionals _like_ `%bcond_without sle11_ifup_compat` and `%bcond_with sle11_ifup_compat`, conditionally move them to a `wicked-sle11-ifup-compat`, ...

2020-12-02 10:23 UTC, lnussel commented
the code doesn't remove anything as long as %usrmerge isn't set and that is not the case anywhere yet. So a total noop for released distros

2020-12-03 15:29 UTC, lnussel commented
I've tweaked the pr to make it even more clear what's  going on.

2021-01-13 10:18 UTC, lnussel commented
Any comment on the updated pr?

2021-01-15 13:53 UTC, mtomaschewski commented
Yes: the code changes neither changed our priorities about this issue nor anything else that I've mentioned before.
I'll not accept an external variable causing to build RPMs breaking sle11 compatibility once you decided to define this flag somewhere.

2021-01-15 15:32 UTC, lnussel commented
You lost me here. From what I can see nothing breaks for sle11. %usrmerged will never be set there. It's to be defined in Factory once all packages are prepared. See also
https://en.opensuse.org/openSUSE:Usr_merge#Preparation

2021-01-15 15:47 UTC, lnussel commented
Wait, you mean your concern is that `/sbin/ifup` won't exist anymore after `%usrmerged ` is set? That's not the case. After usr***merge*** both `/sbin` and `/usr/sbin` refer to the same location. So even though `ifup` will be installed as `/usr/sbin/ifup`, calling `/sbin/ifup` will still work as `/sbin` is a symlink to `/usr/sbin` (just like `bin`, `lib` and `lib64`).

2021-02-15 14:08 UTC, mtomaschewski approved these changes
> Wait, you mean your concern is that `/sbin/ifup` won't exist anymore after `%usrmerged ` is set? [...] calling `/sbin/ifup` will still work as `/sbin` is a symlink to `/usr/sbin` (just like `bin`, `lib` and `lib64`).

OK, `/sbin` will be a symlink to `/usr/sbin` and  there is a clear description of the intention of the pull request with reference to the [UsrMerge](https://en.opensuse.org/openSUSE:Usr_merge) page.

2021-02-15 14:10 UTC, merged

2021-02-23 16:03 UTC, lnussel commented
What's the ETA for landing this in Factory?