wireless: Remove dependencies on libiw-devel
openSUSE/wicked pull request #911
Opened 2022-04-25 11:34 UTC by cfconrad

It was only used to determine if a interface name belongs to a
wireless interface or not.
Unfortunately netlink do not provide this info in the NEWLINK message,
But sysfs tell us if a interface has a wireless extension, once a
/sys/class/net/<ifname>/wireless directory exists.

Issue: https://github.com/openSUSE/wicked/issues/910

2022-04-25 13:12 UTC, mtomaschewski requested changes
```
It was only used to determine if a interface name belongs to a
wireless interface or not.
Unfortunately netlink do not provide this info in the NEWLINK message,
But sysfs tell us if a interface has a wireless extension, once a
/sys/class/net//wireless directory exists.
```

Please use more explicit `rtnetlink` instead just netlink. Also `do` -> `does`, `tell` -> `tells`, `But` -> `but` (or end the sententce and start new one).

I'd suggest:

Remove `libiw` dependency (since https://github.com/openSUSE/wicked/pull/872)
used to detect wireless interfaces only.  Unfortunately `rtnetlink(7)` does not
provide this info in the `NEWLINK` message, so we're using sysfs telling us if
an interface has a wireless extension, once the `/sys/class/net/$name/wireless`
directory exists (issue https://github.com/openSUSE/wicked/issues/910).

2022-04-25 13:12 UTC, mtomaschewski commented on src/iflist.c
> +			/*  Netlink does not tell us if the device has a
Please use `rtnetlink` unstead of (unspecified)netlink:
```
/*  rtnetlink does not tell us if the device has a
*  wireless extenstions or not, but sysfs does. */
```
Also `extention` is incorrect spelling of `extension`.

2022-04-25 13:27 UTC, cfconrad commented
requested changed applied

2022-04-28 12:38 UTC, mtomaschewski approved these changes
Thanks, LGTM.

2022-04-28 12:43 UTC, merged