socket.c improvements and unit tests
openSUSE/wicked pull request #914
Opened 2022-05-19 15:52 UTC by cfconrad

This PR is the second outcome of (bsc#1192508) and the continues work started with 
https://github.com/openSUSE/wicked/pull/912 . 
The `src/socket.c` module had some possible issues in special cases, which solved with
these changes. To avoid regressions, I created a unit test suit for that module, which show the issues in
the old implementation.
Also some code cleanup in dbus was added, where we had wrong refcount handling of `ni_socket_t` objects.

2022-05-30 12:01 UTC, mtomaschewski requested changes
- The commit 6c0a08b says:
```
testing: Run tests within valgrind mem-check

To do so, we use the automake `test-driver` and adopt it
to the functionality of valgrind.
```
But it does not provide the test-driver with --valgrind support any more.
- After a `make check` run, there are untracked files:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	testing/socket-mock-test.log
	testing/socket-mock-test.trs
	testing/test-suite.log

nothing added to commit but untracked files present (use "git add" to track)
```

2022-05-30 15:53 UTC, cfconrad commented
Good catch.
Last changes should avoid these and also the `test-driver` should be there.

2022-05-31 18:35 UTC, mtomaschewski approved these changes
Hmm... almost. It works fine now... except of the fact, that `autogen.sh` (`autoreconf`) overwrites the test-driver with the `--valgrind=yes/no` addition...:
```
$ git status
On branch pull-914-3
Your branch is up to date with 'github/pull/914/head'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   test-driver

no changes added to commit (use "git add" and/or "git commit -a")
$ git diff
diff --git a/test-driver b/test-driver
index db1a2378..d86cf694 100755
--- a/test-driver
+++ b/test-driver
@@ -1,8 +1,9 @@
-#!/bin/sh
+#! /bin/sh
 # test-driver - basic testsuite driver script.
-#
+
+scriptversion=2016-01-11.22; # UTC
+
 # Copyright (C) 2011-2017 Free Software Foundation, Inc.
-# Copyright (C) 2022 SUSE LLC
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
[...]
```

2022-05-31 19:21 UTC, mtomaschewski commented
@cfconrad Perhaps we should use the standard test-driver first and take a separate / deeper look at e.g.:

- https://www.gnu.org/software/gnulib/manual/html_node/Running-self_002dtests-under-valgrind.html
- https://www.gnu.org/software/autoconf-archive/ax_valgrind_check.html

later?

2022-05-31 21:20 UTC, cfconrad commented
urgs, I didn't realized it, sorry!
Yes I think so too, I removed d2e04e25b1064b308f66c32e7c8812d5b7c794c5 from this PR.
This https://www.gnu.org/software/autoconf-archive/ax_valgrind_check.html looks very promising! Thanks for the pointer!

2022-06-01 10:27 UTC, mtomaschewski approved these changes
OK, then lets merge it.

2022-06-01 10:28 UTC, merged