wireless-ifcfg: Ignore WIRELESS_EAP_AUTH within TLS (bsc#1211026)
openSUSE/wicked pull request #969
Opened 2023-05-11 08:41 UTC by cfconrad

2023-05-11 10:56 UTC, mtomaschewski requested changes
Commit dates not incremental -- please fix  the autor date to commit date or don't rebase on top of changes  that are  in the future (but on top of last release aka version-0.7.20 or version-0.6.72):
- commit 5f0031660a4ab689ebe91eb596d92c1ac2476f61
  - Tue **May 9** 13:28:43 2023 +0200
- commit b03f6f92a236393c4a1fa3f1e917211a0342860d
  - Date:   Thu **May 11** 10:34:12 2023 +0200

2023-05-11 11:12 UTC, cfconrad commented
It's on top of the latest master!  That's where I wanna merge it to. Didn't knew that you like to see the date in chronological order, sorry. I will update.

2023-05-12 08:01 UTC, mtomaschewski approved these changes
OK, works for me, a ifcfg-wlan0 with (indexed with _1 in my case):
```
WIRELESS_AUTH_MODE_1=eap
WIRELESS_EAP_MODE_1=tls
WIRELESS_EAP_AUTH_1=mschapv2
```
does not cause  to generate the (serialization) xml ifconfig node:
```diff
         <wpa-eap>
           <method>tls</method>
           <identity>pandora</identity>
-          <phase2>
-            <method>mschapv2</method>
-          </phase2>
         </wpa-eap>
```
and a later error/failure:
```
May 12 09:51:45 pandora wickedd-nanny[3777]: <buffer>:34: <phase2> lacks mandatory <password> child element
May 12 09:51:45 pandora wickedd-nanny[3777]: device wlan0: interface document error
```
but a warning and successful `ifup` instead:
```
pandora:/etc/sysconfig/network # ifup wlan0
wicked: ifcfg-wlan0: Ignore WIRELESS_EAP_AUTH_1 for eap mode TLS
wlan0           up
```

2023-05-12 08:02 UTC, merged

2023-05-12 08:13 UTC, mtomaschewski commented
See also  https://github.com/yast/yast-network/pull/1331 and https://github.com/yast/yast-network/pull/1332.